seed: 73
cuda: 0 # use_gpu
# RAM: ~10G
env:
  env_type: nasim
  env_name: MediumGenPO-v0

  num_eval_tasks: 20

train:
  # 250*1000 = 250.000 total steps max.
  # 1000 is the env step limit.
  num_iters: 200 # number meta-training iterates
  num_init_rollouts_pool: 15 # before training
  # Note on init rollouts: If the env is more complex it might be a good idea
  # to collect more initial rollouts
  num_rollouts_per_iter: 1

  num_updates_per_iter: 0.5

  # buffer params
  buffer_size: 1e6
  batch_size: 32 # to tune based on sampled_seq_len
  sampled_seq_len: -1 # -1 is all, or positive integer
  sample_weight_baseline: 0.0

eval:
  eval_stochastic: false # also eval stochastic policy
  log_interval: 5 # Number of iterations
  save_interval: -1
  log_tensorboard: true

policy:
  separate: True
  seq_model: lstm # [lstm, gru]
  algo_name: sacd # only support sac-discrete

  action_embedding_size: 8 # no action input
  observ_embedding_size: 32
  reward_embedding_size: 8
  rnn_hidden_size: 128

  dqn_layers: [128, 128]
  policy_layers: [128, 128]
  lr: 0.0003
  gamma: 0.99
  tau: 0.005

  sacd:
    entropy_alpha: null
    automatic_entropy_tuning: true
    target_entropy: 0.7 # the ratio: target_entropy = ratio * log(|A|)
    alpha_lr: 0.0003

